name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn package

    - name: Create and checkout build branch
      run: |
        git checkout build
        git pull origin build || true
        git rm -rf .
        git checkout master -- out/
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Add built files"
        git push origin build
